spring.application.name=SpringSecurityH2Auth
# H2 Database Configuration
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Make sure JPA creates and updates tables based on our entities
spring.jpa.hibernate.ddl-auto=update

# This is the magic line:
# Adding this line to avoid the race condition between running the data.sql and @Entity by the spring boot
# Sometimes data.sql will run first before entity actually creates the table
# It tells Spring Boot to wait until Hibernate has created the tables
# BEFORE running the data.sql script.
spring.jpa.defer-datasource-initialization=true